### ISSUE TITLE
feedback about node_modules

### ISSUE THREAD

**Issue by fibo** [pro-react/pro-react.github.io#1]
Hi,

I write here hoping it is the right place to give a feedback. I read your webpack appendix and I noticed you add to your package.json something like _node_modules/.bin/webpack_.

Please update your material, it is not necessary to add the relative path cause npm already add the .bin folder to your path. Just putting "webpack" will work.

See for example my [npm tiny package article](http://g14n.info/2015/12/tiny-npm-package/).

**Comment by cassiozen** [comment]
I don't know if this is true in all versions/circumstances. In the computer i'm currently working on, it failed the path:

![print](https://cloud.githubusercontent.com/assets/33676/12719059/e408b1d2-c8d9-11e5-8c7a-5abae9f09536.png)

**Comment by fibo** [comment]
it fails cause you launched it from your shell session. Npm adds bin to your path only inside npm scripts, please read the article linked above, see the npm script which launches standard linter, or see for example this [package.json](https://github.com/fibo/dflow/blob/master/package.json).

**Comment by cassiozen** [comment]
Ok, now I see. Thanks for the feedback, I'll update soon.
