### ISSUE TITLE
"webpack -config" should be "webpack --config"

### ISSUE THREAD

**Issue by Oele** [pro-react/pro-react.github.io#2]
In Appendix A, theres a webpack command line defined as: 

`"build": "NODE_ENV=production webpack -config ./webpack.production.config.js --progress"`

The `-config` should have two dashes (`--config`), otherwise the argument is ignored and the non-production default webpack config is loaded.

**Comment by cassiozen** [comment]
Thanks a lot! I wrote the original document using Word (publisher restrictions) and sometimes it automatically substitutes a double hyphen (--) for a long dash....

Fixed.
